### ISSUE TITLE
 I used the "otool - L CamTrap Detector" . Why is there a difference

### ISSUE THREAD

**Issue by 425776024** [bencevans/camtrap-detector#157]
Hello, why is it that on macOS, after compiling your code, I used the `otool - L CamTrap Detector` and displayed the dependency `/usr/local/opt/opencv/lib/libopencv_core. 407. dylib,...`? I know this is a dependency on my local opencv environment, but it will cause me to share it with other macOS users who have not installed opencv and will not be able to use it, but I downloaded your published [`CamTrap. Detector_0.4.0_x64. dmg`](https://camtrap.net/detector) I used `otool - L CamTrap Detecto` in the package, but it did not display the dependency 'libopencv_xxx. dylib'. Why is there a difference

**Comment by bencevans** [comment]
When building for release we build static versions of OpenCV so that it’ll be bundled in.

**Comment by 425776024** [comment]
Thank you very much. I have resolved it
